version: '3'
services:
  bot:
    container_name: 'UnionEx-Bot'
    image: UnionExBot
    stop_signal: SIGINT
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "3"
